name: Windows MSI / Linux DEB-RPM (jpackage)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch: {}

jobs:
  windows-msi:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Compute version
        id: meta
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" && "${GITHUB_REF_NAME}" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            ver="${BASH_REMATCH[1]}"
          else
            ver="1.0.${GITHUB_RUN_NUMBER}"
          fi
          echo "APP_VERSION=$ver" >> "$GITHUB_ENV"
          echo "APP_INSTALLERTYPE=msi" >> "$GITHUB_ENV"
          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Build MSI installer
        run: |
          ./gradlew --no-daemon jpackage

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hiyori-windows-msi
          path: build/jpackage/*.msi
          if-no-files-found: error

      - name: Create GitHub Release and upload asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Hiyori ${{ steps.meta.outputs.version }}
          files: build/jpackage/*.msi
          draft: false
          prerelease: false
          generate_release_notes: true

  linux-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        pkg: [ deb, rpm ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm fakeroot

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Compute version
        id: meta
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" && "${GITHUB_REF_NAME}" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            ver="${BASH_REMATCH[1]}"
          else
            ver="1.0.${GITHUB_RUN_NUMBER}"
          fi
          echo "APP_VERSION=$ver" >> "$GITHUB_ENV"
          echo "APP_INSTALLERTYPE=${{ matrix.pkg }}" >> "$GITHUB_ENV"
          echo "version=$ver" >> "$GITHUB_OUTPUT"

      - name: Build ${{ matrix.pkg }} installer
        run: |
          ./gradlew --no-daemon jpackage

      - name: Upload ${{ matrix.pkg }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hiyori-linux-${{ matrix.pkg }}
          path: build/jpackage/*.${{ matrix.pkg }}
          if-no-files-found: error

      - name: Create GitHub Release and upload asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Hiyori ${{ steps.meta.outputs.version }}
          files: build/jpackage/*.${{ matrix.pkg }}
          draft: false
          prerelease: false
          generate_release_notes: true

